sudo: false

dist: xenial

language: erlang

otp_release:
 - 20.1.7
 - 20.2.4
 - 20.3.8.2
 - 21.0.2

install: "true"

before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - ./rebar3 compile
  - ./rebar3 do xref, ct, coveralls send

notifications:
  slack:
    secure: "FfunzqgAWYjBclFDTlEseNLiUegv1wHDiz2mrM8K0iQi9fCejONTMekKvhRdznyYyF7mf7kYFh6NTtmSFqeeGbtn5l/lg8BYo7sdcEl5xFa9wBEdhw7coLHniSqA9gLCsnOl8LgKsCy0ZnBCq6qE75zzhnO7K72mngzpvv7hvVvpDyBRfxr/LTkNifAuixLev9PLg4iX5MxZIrr/95fOY7kSrb1SRtdkVQw3NKjNt9mbp69FDoV4tDi43NfC5hc/B8+mwF4ccjrr8M2b5zytn/Y0RR3TqJrUwKUw9L5ybIRgDcz3lBNpBRa3E8PuWyfCvXBMAMAoV5rOCWROg9klv23gCUZ9cqfeZyIJoPdrOGchi44+kWjsyGIo4JdPSzhO1/GUt9pipn41ve8eXPrLkhFg2zB3uoQR9y54sTPUnyXKCWRD+p/Q9C0AtWiNozT73SJ8kqLv1GZ13ZBXwXHJjs5QZz+ZQ3C0TNHNrh2a9GsC73zptobOlbcdQyeK3bEfeVUWXSqVgQcbVnlPnbDJNR3CmL0PgrktY+Et5Se1r3PFkHzmgNVJ0OF12b1wRE0I2DMPWb/GQUTLeNVBUokfJGEsRwRyhQuC1TI8a86zvMYxoViBcDQz5ec9+oDwTmKpN3iLLY/Bv/1gSAPjC9M/+c4hXxVYIPbEmeMgqru9Brs="
